export const AuthActionTypes = {
  CREATE_USER_START: "CREATE_USER_START",
  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_FAIL: "CREATE_USER_FAIL",

  LOGIN_USER_START: "LOGIN_USER_START",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGIN_USER_FAIL: "LOGIN_USER_FAIL",

  SOCIAL_LOGIN_START: " SOCIAL_LOGIN_START",
  SOCIAL_LOGIN_SUCCESS: " SOCIAL_LOGIN_SUCCESS",
  SOCIAL_LOGIN_FAIL: " SOCIAL_LOGIN_FAIL",

  GET_USER_START: " GET_USER_START",
  GET_USER_SUCCESS: " GET_USER_SUCCESS",
  GET_USER_FAIL: " GET_USER_FAIL",

  UPDATE_USER_IMAGE_START: " UPDATE_USER_IMAGE_START",
  UPDATE_USER_IMAGE_SUCCESS: " UPDATE_USER_IMAGE_SUCCESS",
  UPDATE_USER_IMAGE_FAIL: " UPDATE_USER_IMAGE_FAIL",
};
export const MessagesActionTypes = {
  GET_CHAT_START: "GET_CHAT_START",
  GET_CHAT_SUCCESS: "GET_CHAT_SUCCESS",
  GET_CHAT_FAIL: "GET_CHAT_FAIL",

  GET_MESSAGES_START: "GET_MESSAGES_START",
  GET_MESSAGES_SUCCESS: "GET_MESSAGES_SUCCESS",
  GET_MESSAGES_FAIL: "GET_MESSAGES_FAIL",

  SEEN_ALL_MESSAGES_START: " SEEN_ALL_MESSAGES_START",
  SEEN_ALL_MESSAGES_SUCCESS: " SEEN_ALL_MESSAGES_SUCCESS",
  SEEN_ALL_MESSAGES_FAIL: " SEEN_ALL_MESSAGES_FAIL",

  UPDATE_CONTACTS_LOCALLY: "UPDATE_CONTACTS_LOCALLY",
  ADD_MESSAGE_LOCALLY: "ADD_MESSAGE_LOCALLY",
};
export const ModlasActionTypes = {
  SHOW_ADD_NEW_CONTACT_MODAL: "SHOW_ADD_NEW_CONTACT_MODAL",
  SHOW_NEW_CALL_ALERT: "SHOW_NEW_CALL_ALERT",
};
export const SearchActionTypes = {
  SEARCH_USERS_START: "SEARCH_USERS_START",
  SEARCH_USERS_SUCCESS: "SEARCH_USERS_SUCCESS",
  SEARCH_USERS_FAIL: "SEARCH_USERS_FAIL",
};
